language: go

sudo: false

gobuild_args: -v -race -tags ci
before_script:
  - go vet ./...
install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
deploy:
  provider: heroku
  api_key:
    secure: oPXoJBzvrOfzQWDVsMCBqzXzLq5nus9qyFURzkFakyNkbVzOieLiBcxbHLTNAQerYRzwEyAcOAuGJi+Rl1Fcy52qxSUdB8qT7a1PgGdURmwlpRAIcv31mSNlVCgwQAP2bineaZUo8AcOH9rEIS/90Sp/5rhx/GdPKtNutmC2W/Vfl0IrigqOIj21p5TbUzLulOgQDUUZcJWnMqhsxNPCKCqihQRm3/Ft/zPaXpu4FOZBcNkpgiIWeyXRd+MipCqBmtVZYQeuC4zs4+pjrWgPCIMmWlpJkMzOIzsa0rxhe1hMljRuJXAK8jSh1SxqkM8G3vJbYYqMKtpd1bqtTqAyMlJZ2engxKkR6jNR2oLwFHRd7Riqn4UWaEqYWIBijaAYvsK2ELE0q/iaKX/c4ex2XPupbJZdDvHyeMf9coKPZj2R47KSPW/HKJwEB42MluhlWFFyLeO/+jjZTAvp7d0TMVl5PDM+42ZLhEVn4P12vNaxle5MtrD4pUnIs2uiwmgp27i3YwVtrLTe9qcz3mBl897FKlOL6571oTaHeDmvSsPYep8AkeDHqRGt6LFtWQ4mJgqmEmmk98D6FtVr8manvqS1JDvdvezMYunwr/mXVbIUgyQzFLMrDSFyggGpSzKrCHxJ2xtFTWWumr/T4tFE4hBZCq5LXBITol3JnxrVOcE=
  on:
    repo: benknoble/game-roulette
notifications:
  mail: false

# vim: nowrap
